import json

with open("app/data/info.json", "r", encoding="utf-8") as f:
    data = json.load(f)

for author in data:
    # Fix the 3 images
    if author["id"] in ["cheikh-anta-diop", "joseph-ki-zerbo", "muyiwa-falaiye"]:
        author["image"] = author["image"].replace(".jpg", ".jpeg")
    
    # Fix longDescription for Koya
    if author["id"] == "cresantia-frances-koya":
        author["longDescription"] = "Cresantia Frances Koya Vaka'uta é uma influente escritora, poeta, artista e cientista social fijiana de ascendência samoana, cujo trabalho cruza educação, sustentabilidade, multiculturalismo e identidade cultural na Oceania. Com uma longa trajetória na University of the South Pacific (onde atuou como Diretora do Centro de Artes, Cultura e Estudos do Pacífico da UNESCO e Diretora Associada de Pesquisa), Koya Vaka'uta posiciona-se como uma importante pensadora regional, utilizando também o pseudônimo artístico e ativista “1angrynative” para criar poesias de protesto que abordam as crises contemporâneas das ilhas.\n\nO núcleo de sua produção intelectual e metodológica concentra-se na descolonização dos sistemas educativos e nas epistemologias e metodologias de pesquisa indígenas do Pacífico. Por se identificar como cidadã de Fiji, mas de origem samoana, ela opta eticamente por não pesquisar diretamente os sistemas de conhecimento tradicionais dos fijianos nativos, preferindo teorizar sobre conceitos de nacionalismo, transculturalidade e identidades na Oceania. Koya Vaka'uta defende vigorosamente uma \"reestruturação educacional\" onde os saberes holísticos locais (que interligam de forma inseparável a cultura, o oceano, as artes patrimoniais e o meio ambiente) sirvam de base para um desenvolvimento verdadeiramente sustentável e para a construção da resiliência nas novas gerações, rejeitando as categorizações rígidas e os paradigmas imperialistas impostos pelo pensamento ocidental moderno."
    
    # Fix longDescription for Linda
    if author["id"] == "linda-tuhiwai-smith":
        author["longDescription"] = "A Dra. Linda Tuhiwai Smith é uma proeminente intelectual e educadora Māori da Nova Zelândia, amplamente reconhecida como uma das maiores referências mundiais em estudos decoloniais e educação indígena. Ao longo de sua carreira (com passagens de liderança na University of Waikato e no Te Whare Wānanga o Awanuiārangi), Smith tem sido uma força transformadora na academia global, advogando pela autodeterminação dos povos originários (Tino Rangatiratanga) através da reestruturação dos modos de se produzir ciência.\n\nA essência de sua contribuição teórica e metodológica reside na crítica profunda à matriz colonial da ciência ocidental. Em sua obra clássica “Decolonizing Methodologies”, ela demonstra como a pesquisa convencional historicamente serviu como um instrumento de colonização, extração e desumanização das comunidades nativas. Em contrapartida, Smith propõe uma agenda de pesquisa fundamentada nas epistemologias indígenas (com destaque para o Kaupapa Māori), defendendo que os métodos de investigação devem ser centralizados na justiça social, na ética local, na cura e na revitalização dos conhecimentos tradicionais. Para a autora, a descolonização da metodologia não é apenas uma escolha teórica, mas um ato político de sobrevivência e emancipação que devolve aos povos indígenas o direito de contar e teorizar suas próprias histórias."
        
    # Fix longDescription for Toon
    if author["id"] == "toon-van-meijl":
        author["longDescription"] = "Toon van Meijl é um renomado antropólogo cultural neerlandês e professor emérito da Radboud University Nijmegen (Países Baixos). Especialista de destaque internacional na região do Pacífico, ele construiu grande parte do seu legado acadêmico por meio de uma densa pesquisa etnográfica de longo prazo junto ao povo Māori (especialmente a confederação tribal Tainui, na Nova Zelândia), iniciada em 1982. A sua abordagem multidisciplinar transita entre a antropologia política, a psicologia transcultural e a sociologia do conhecimento, focando-se em dinâmicas de identidade cultural, globalização e direitos de propriedade indígena.\n\nNo âmbito da epistemologia, van Meijl oferece uma perspectiva analítica externa e reflexiva de extrema relevância, voltada para o que designa como \"fazer epistemologia indígena\". Ele investiga os debates internos nas sociedades tradicionais sobre o \"conhecimento de dentro\" (inside knowledge), analisando as tensões e distinções estruturais entre os modelos científicos eurocêntricos e os sistemas nativos de validação da verdade. O autor desconstrói as abordagens essencialistas da cultura (como no debate em torno do conceito de Maoritanga ou \"modo de ser Māori\"), argumentando que o conhecimento indígena não é estático nem puramente herdado, mas um processo dinâmico, negociável e ativamente reformulado pelos próprios sujeitos em contextos modernos e urbanos. Além disso, van Meijl é um defensor da \"antropologia engajada\", equilibrando o rigor metodológico ocidental com o compromisso ético de apoiar as reivindicações políticas e identitárias das comunidades que estuda."
        
with open("app/data/info.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Updated JSON")
